[phases.setup]
nixpkgs = ["python310"]

[phases.install]
commands = [
  "apk add --no-cache python3 py3-pip",  # Install Python3 and pip
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]


[phases.debug]
commands = [
  "python3 --version",
  "python3 -m pip --version",
  "ls -l"  # List files to verify paths
]


[phases.start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
