[phases.setup]
nixpkgs = ["python310"]

[phases.install]
commands = [
  "python3 -m ensurepip --upgrade",  # Ensure pip is installed
  "python3 -m pip install --upgrade pip",  # Upgrade pip
  "python3 -m pip install -r requirements.txt"  # Install dependencies
]

[phases.start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
