[phases.setup]
nixpkgs = ["python310", "pip", "build-essential", "libffi", "libssl", "libfreetype", "libpng", "libopenblas", "git"]

[phases.install]
commands = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
commands = ["uvicorn backend.main:app --host 0.0.0.0 --port 8000"]

[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]