[phases.setup]
nixpkgs = ["python310"]

[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
